![img](https://drive.google.com/uc?export=view&id=1kgX98Ziw9LzgBCT2BxChttfrTcBltLej)

# PRÁCTICO 5

  Crear una lista con los datos de **población** de las provincias de Argentina: 2890151,15625084,367828,1055259,509108,3308876,992595,1235994,530162,673307,318951,333642,1738929,1101593,551266,638645,1214441,681055,432310,273964,3194537,874006,127205,1448188

Nombrarla como: poblacion_prov


In [74]:
poblacion_prov=[2890151,15625084,367828,1055259,509108,3308876,992595,1235994,530162,673307,318951,333642,1738929,1101593,551266,638645,1214441,681055,432310,273964,3194537,874006,127205,1448188]

  Crear una lista con los datos de **superficie**  de las provincias de Argentina: 200,307571,102602,99633,224686,165321,88199,78781,72066,53219,143440,89680,148827,29801,94078,203013,155488,89651,76748,243943,133007,136351,1002445,22524

Nombrarla como: superficie_prov


In [75]:
 superficie_prov=[200,307571,102602,99633,224686,165321,88199,78781,72066,53219,143440,89680,148827,29801,94078,203013,155488,89651,76748,243943,133007,136351,1002445,22524]

In [76]:
print(type(poblacion_prov),type(superficie_prov))

<class 'list'> <class 'list'>


Importar el paquete *numpy* como *np*

In [77]:
import numpy as np

Crear un array a partir de poblacion_prov: a_pob_prov

In [78]:
a_Pob_prov=np.array(poblacion_prov)
a_Pob_prov

array([ 2890151, 15625084,   367828,  1055259,   509108,  3308876,
         992595,  1235994,   530162,   673307,   318951,   333642,
        1738929,  1101593,   551266,   638645,  1214441,   681055,
         432310,   273964,  3194537,   874006,   127205,  1448188])

Crear un array a partir de superficie: a_sup_prov

In [79]:
a_Sup_prov=np.array(superficie_prov)
a_Sup_prov

array([    200,  307571,  102602,   99633,  224686,  165321,   88199,
         78781,   72066,   53219,  143440,   89680,  148827,   29801,
         94078,  203013,  155488,   89651,   76748,  243943,  133007,
        136351, 1002445,   22524])

Imprimir los tipos los dos ultimos objetos creados: *a_pob_prov*   y *a_sup_prov*

In [80]:
print(type(a_Pob_prov),type(a_Sup_prov))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


A partir de la lista  *pob_provincias*, crear un array de numpy con los datos de la **población en millones de habitantes** llmarlo Pob_prov_millones


In [81]:
Pob_prov_millones= np.array(poblacion_prov) /1000000
#Pob_prov_millones
print(Pob_prov_millones)

[ 2.890151 15.625084  0.367828  1.055259  0.509108  3.308876  0.992595
  1.235994  0.530162  0.673307  0.318951  0.333642  1.738929  1.101593
  0.551266  0.638645  1.214441  0.681055  0.43231   0.273964  3.194537
  0.874006  0.127205  1.448188]


Calcular la **densidad poblacional** (pob/km2): densidad_pob_prov

In [82]:
densidad_pob_prov= a_Pob_prov / a_Sup_prov
print(densidad_pob_prov)
type(densidad_pob_prov)

[14450.755         50.80155151     3.58499834    10.59146066
     2.26586436    20.01485595    11.25403916    15.68898592
     7.35661755    12.65162818     2.22358477     3.72036128
    11.68423068    36.96496762     5.85966964     3.14583303
     7.81051271     7.59673623     5.63285037     1.12306563
    24.01781109     6.40997132     0.12689474    64.29532943]


numpy.ndarray

Para quitar la notación científica al imprimir una manera posible en numpy es:

In [83]:
np.set_printoptions(suppress=True)
print(densidad_pob_prov)

[14450.755         50.80155151     3.58499834    10.59146066
     2.26586436    20.01485595    11.25403916    15.68898592
     7.35661755    12.65162818     2.22358477     3.72036128
    11.68423068    36.96496762     5.85966964     3.14583303
     7.81051271     7.59673623     5.63285037     1.12306563
    24.01781109     6.40997132     0.12689474    64.29532943]


Declarar una variable *prov_densa_pobladas* que contega las provincias cuya densidad de población sea superior a 50 hab/km2 

In [84]:
prov_densa_pobladas = densidad_pob_prov>50
print(prov_densa_pobladas)
type(prov_densa_pobladas)
# Notar que los datos del array (o vector) anterior son de tipo booleanos: cumple o no comple la condición >50

[ True  True False False False False False False False False False False
 False False False False False False False False False False False  True]


numpy.ndarray

Imprimir los valores que se corresponden a provincias densamente poblados

In [85]:
print(densidad_pob_prov[densidad_pob_prov>50])

[14450.755         50.80155151    64.29532943]


# PRÁCTICO 6

![img](https://drive.google.com/uc?export=view&id=1q-UDGlNu9zoxc3z2rWz1kitaeFgsAy1P)

Crear un array que contenga los datos de "población" y "superficie en km2" (es decir dos columnas) de cada provincia (24 filas) , a partir [población , superficie]

nombrarlo "provincias"  
Datos: [Población,Superficie_km²]

2890151,200
15625084,307571
367828,102602
1055259,99633
509108,224686
3308876,165321
992595,88199
1235994,78781
530162,72066
673307,53219
318951,143440
333642,89680
1738929,148827
1101593,29801
551266,94078
638645,203013
1214441,155488
681055,89651
432310,76748
273964,243943
3194537,133007
874006,136351
127205,1002445
1448188,22524


In [86]:
provincias= [[2890151,200],
[15625084,307571],
[367828,102602],
[1055259,99633],
[509108,224686],
[3308876,165321],
[992595,88199],
[1235994,78781],
[530162,72066],
[673307,53219],
[318951,143440],
[333642,89680],
[1738929,148827],
[1101593,29801],
[551266,94078],
[638645,203013],
[1214441,155488],
[681055,89651],
[432310,76748],
[273964,243943],
[3194537,133007],
[874006,136351],
[127205,1002445],
[1448188,22524]
]
print(provincias)
type(provincias)

# notar que no responde a la consigan... en realidad hemos creado una lista

[[2890151, 200], [15625084, 307571], [367828, 102602], [1055259, 99633], [509108, 224686], [3308876, 165321], [992595, 88199], [1235994, 78781], [530162, 72066], [673307, 53219], [318951, 143440], [333642, 89680], [1738929, 148827], [1101593, 29801], [551266, 94078], [638645, 203013], [1214441, 155488], [681055, 89651], [432310, 76748], [273964, 243943], [3194537, 133007], [874006, 136351], [127205, 1002445], [1448188, 22524]]


list

In [87]:
import numpy as np
np_provincias= np.array(provincias)
print(np_provincias)
type(np_provincias)

[[ 2890151      200]
 [15625084   307571]
 [  367828   102602]
 [ 1055259    99633]
 [  509108   224686]
 [ 3308876   165321]
 [  992595    88199]
 [ 1235994    78781]
 [  530162    72066]
 [  673307    53219]
 [  318951   143440]
 [  333642    89680]
 [ 1738929   148827]
 [ 1101593    29801]
 [  551266    94078]
 [  638645   203013]
 [ 1214441   155488]
 [  681055    89651]
 [  432310    76748]
 [  273964   243943]
 [ 3194537   133007]
 [  874006   136351]
 [  127205  1002445]
 [ 1448188    22524]]


numpy.ndarray

In [88]:
print(np_provincias.shape)  # dimensión de la matriz

(24, 2)


Imprimir la fila número 18 completa (todos los valores de esa fila, en este caso son sólo dos datos) 

In [89]:
print(np_provincias[20,:])

[3194537  133007]


seleccionar la segunda columna y almacenarla en la variable np_superficie

In [90]:
np_superfice=np_provincias[:,1]
np_superfice #continua siendo tipo array de 24x1
print(np_superfice)

[    200  307571  102602   99633  224686  165321   88199   78781   72066
   53219  143440   89680  148827   29801   94078  203013  155488   89651
   76748  243943  133007  136351 1002445   22524]


Imprimir la poblacion de la 8° provincia


In [91]:
print(np_provincias[7,:1]) # notar que los el 7 es inclusivo contando desde poisición cero, devuelve la 8. Y el :1 no incluye el valor 1...
print(np_provincias[7,0]) #permite extaer el dato en esa posición 
print(type(np_provincias[7,:1]))
print(type(np_provincias[7,0]))

[1235994]
1235994
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [92]:
#type(np_provincias[7,:1]) # notar que los el 7 es inclusivo contando desde poisición cero, devuelve la 8. Y el :1 no incluye el valor 1...
type(np_provincias[7,0])

numpy.int64

Calcular la *densidad poblacional* y almacenarla en el vector np_densidad

In [93]:
np_densidad = np_provincias[:,0]/np_provincias[:,1]

In [94]:
np.set_printoptions(suppress=True)
print(np_densidad)

[14450.755         50.80155151     3.58499834    10.59146066
     2.26586436    20.01485595    11.25403916    15.68898592
     7.35661755    12.65162818     2.22358477     3.72036128
    11.68423068    36.96496762     5.85966964     3.14583303
     7.81051271     7.59673623     5.63285037     1.12306563
    24.01781109     6.40997132     0.12689474    64.29532943]


Agregar al array la columna *densidad* y crear el array np_provincias_completo (con tres columnas)

In [95]:
np_provincias_completo = np.c_[np_provincias, np_densidad]  ##np.c_ concatena los vectores en columnas
print(np_provincias_completo)
np_provincias_completo.shape

[[ 2890151.              200.            14450.755     ]
 [15625084.           307571.               50.80155151]
 [  367828.           102602.                3.58499834]
 [ 1055259.            99633.               10.59146066]
 [  509108.           224686.                2.26586436]
 [ 3308876.           165321.               20.01485595]
 [  992595.            88199.               11.25403916]
 [ 1235994.            78781.               15.68898592]
 [  530162.            72066.                7.35661755]
 [  673307.            53219.               12.65162818]
 [  318951.           143440.                2.22358477]
 [  333642.            89680.                3.72036128]
 [ 1738929.           148827.               11.68423068]
 [ 1101593.            29801.               36.96496762]
 [  551266.            94078.                5.85966964]
 [  638645.           203013.                3.14583303]
 [ 1214441.           155488.                7.81051271]
 [  681055.            89651.  

(24, 3)

In [96]:
#Otra alternativa puede ser:
np_provincias_completo_2 = np.column_stack((np_provincias, np_densidad)) #np.r_ concatena los vectores en filas
# con método .column_stack requiere que el parámetro que se ingresa sea una tupla.
np_provincias_completo_2

array([[ 2890151.        ,      200.        ,    14450.755     ],
       [15625084.        ,   307571.        ,       50.80155151],
       [  367828.        ,   102602.        ,        3.58499834],
       [ 1055259.        ,    99633.        ,       10.59146066],
       [  509108.        ,   224686.        ,        2.26586436],
       [ 3308876.        ,   165321.        ,       20.01485595],
       [  992595.        ,    88199.        ,       11.25403916],
       [ 1235994.        ,    78781.        ,       15.68898592],
       [  530162.        ,    72066.        ,        7.35661755],
       [  673307.        ,    53219.        ,       12.65162818],
       [  318951.        ,   143440.        ,        2.22358477],
       [  333642.        ,    89680.        ,        3.72036128],
       [ 1738929.        ,   148827.        ,       11.68423068],
       [ 1101593.        ,    29801.        ,       36.96496762],
       [  551266.        ,    94078.        ,        5.85966964],
       [  

# PRÁCTICO 7

A partir de los siguientes datos crear un *diccionario* *provincias* a partir de las listas que contenga las primeras 7 provincias.

pob_provincias = [15625084, 273964, 509108, 638645, 3308876, 1214441, 1738929, 318951, 874006, 3194537, 367828, 1055259, 585126, 333642, 681055, 930911, 1235994, 432310, 530162, 673307, 1101593, 1448188, 127205]
sup_provincias = [307571, 243943, 224686, 203013, 165321, 155488, 148827, 143440, 136351, 133007, 102602, 99633, 94078, 89680, 89651, 88199, 78781, 76748, 72066, 53219, 29801, 22524, 21571]
nom_provincias = ["Buenos Aires", "Santa Cruz", "Chubut", "Río Negro", "Córdoba", "Salta", "Mendoza", "La Pampa", "Santiago del Estero", "Santa Fe", "Catamarca", "Chaco", "Neuquén", "La Rioja", "San Juan", "Corrientes", "Entre Ríos", "San Luis", "Formosa", "Jujuy", "Misiones", "Tucumán", "Tierra del Fuego, Antártida e Islas del Atlántico Sur"]

In [98]:
pob_prov = [15625084, 273964, 509108, 638645, 3308876, 1214441, 1738929, 318951, 874006, 3194537, 367828, 1055259, 585126, 333642, 681055, 930911, 1235994, 432310, 530162, 673307, 1101593, 1448188, 127205]
sup_prov = [307571, 243943, 224686, 203013, 165321, 155488, 148827, 143440, 136351, 133007, 102602, 99633, 94078, 89680, 89651, 88199, 78781, 76748, 72066, 53219, 29801, 22524, 21571]
nom_prov = ["Buenos Aires", "Santa Cruz", "Chubut", "Río Negro", "Córdoba", "Salta", "Mendoza", "La Pampa", "Santiago del Estero", "Santa Fe", "Catamarca", "Chaco", "Neuquén", "La Rioja", "San Juan", "Corrientes", "Entre Ríos", "San Luis", "Formosa", "Jujuy", "Misiones", "Tucumán", "Tierra del Fuego, Antártida e Islas del Atlántico Sur"]
np_pob_prov = np.array(pob_prov) 
np_sup_prov = np.array(sup_prov)
np_densidad_poblacional = np_pob_prov / np_sup_prov

Crear un diccionario a partir de las tres listas que contenga las primeras 7 provincias

In [99]:
nom_prov[0]
provincias = {
            nom_prov[0]:np_densidad_poblacional[0],
            nom_prov[1]:np_densidad_poblacional[1],
            nom_prov[2]:np_densidad_poblacional[2],
            nom_prov[3]:np_densidad_poblacional[3],
            nom_prov[4]:np_densidad_poblacional[4],
            nom_prov[5]:np_densidad_poblacional[5],
            nom_prov[6]:np_densidad_poblacional[6]
        }

Imprima el dicconario, las keys del mismo y los valores correspondientes

In [100]:
print(provincias)
print(provincias.keys())
print(provincias.values())

{'Buenos Aires': 50.80155151168348, 'Santa Cruz': 1.1230656341850351, 'Chubut': 2.2658643618204963, 'Río Negro': 3.1458330254712754, 'Córdoba': 20.014855946915397, 'Salta': 7.810512708376209, 'Mendoza': 11.684230683948478}
dict_keys(['Buenos Aires', 'Santa Cruz', 'Chubut', 'Río Negro', 'Córdoba', 'Salta', 'Mendoza'])
dict_values([50.80155151168348, 1.1230656341850351, 2.2658643618204963, 3.1458330254712754, 20.014855946915397, 7.810512708376209, 11.684230683948478])


Imprimir el valor del diccionario para la key "Buenos Aires"

In [101]:
print(provincias["Buenos Aires"])

50.80155151168348


# PRÁCTICO 8


Agregar al diccionario provincia "Santa Fe"


In [102]:
ind = nom_prov.index("Santa Fe")
ind
provincias[nom_prov[ind]]=np_densidad_poblacional[ind]
provincias

{'Buenos Aires': 50.80155151168348,
 'Chubut': 2.2658643618204963,
 'Córdoba': 20.014855946915397,
 'Mendoza': 11.684230683948478,
 'Río Negro': 3.1458330254712754,
 'Salta': 7.810512708376209,
 'Santa Cruz': 1.1230656341850351,
 'Santa Fe': 24.01781109264926}

Borrar del diccionario la provincia *Chubut*. Use *del()*


In [106]:
del(provincias["Chubut"])
provincias

{'Buenos Aires': 50.80155151168348,
 'Córdoba': 20.014855946915397,
 'Mendoza': 11.684230683948478,
 'Río Negro': 3.1458330254712754,
 'Salta': 7.810512708376209,
 'Santa Cruz': 1.1230656341850351,
 'Santa Fe': 24.01781109264926}

También se pueden crear Diccionario de diccionarios... Intente uno que contega todas las provincias. Guardarlo en *todas_prov*


In [110]:
todas_prov = {
        nom_prov[0]:{"poblacion":pob_prov[0],"superficie":sup_prov[0], "densidad_poblacional":np_densidad_poblacional[0]},
        nom_prov[1]:{"poblacion":pob_prov[1],"superficie":sup_prov[1], "densidad_poblacional":np_densidad_poblacional[1]},
        nom_prov[2]:{"poblacion":pob_prov[2],"superficie":sup_prov[2], "densidad_poblacional":np_densidad_poblacional[2]},
        nom_prov[3]:{"poblacion":pob_prov[3],"superficie":sup_prov[3], "densidad_poblacional":np_densidad_poblacional[3]},
        nom_prov[4]:{"poblacion":pob_prov[4],"superficie":sup_prov[4], "densidad_poblacional":np_densidad_poblacional[4]}
        }
print(todas_prov)

{'Buenos Aires': {'poblacion': 15625084, 'superficie': 307571, 'densidad_poblacional': 50.80155151168348}, 'Santa Cruz': {'poblacion': 273964, 'superficie': 243943, 'densidad_poblacional': 1.1230656341850351}, 'Chubut': {'poblacion': 509108, 'superficie': 224686, 'densidad_poblacional': 2.2658643618204963}, 'Río Negro': {'poblacion': 638645, 'superficie': 203013, 'densidad_poblacional': 3.1458330254712754}, 'Córdoba': {'poblacion': 3308876, 'superficie': 165321, 'densidad_poblacional': 20.014855946915397}}


Obtener del diccionario completo, los valores correspondientes a la provincia de *Río Negro*

In [113]:
print(todas_prov["Río Negro"]) 

{'poblacion': 638645, 'superficie': 203013, 'densidad_poblacional': 3.1458330254712754}
